# Generated by Django 3.2.15 on 2022-09-20 17:01

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_alter_job_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(default='', upload_to=job.models.Job.image_upload),
        ),
    ]
